import { computeTotals } from '../utils/calculations';
import { fmt, monthLabel } from '../utils/helpers';

function printSlip(r, monthKey) {
  const label = monthLabel(monthKey);
  const bal = r.total;
  const balText = bal > 0 ? ' (Due)' : bal < 0 ? ' (Extra)' : '';
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment Slip - ${r.member}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Courier New', monospace; padding: 40px 20px; max-width: 400px; margin: auto; }
  h1 { font-size: 20px; text-align: center; margin-bottom: 4px; }
  .period { text-align: center; color: #666; font-size: 14px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; font-size: 15px; }
  td { padding: 8px 6px; border-bottom: 1px dashed #ccc; }
  td:last-child { text-align: right; font-weight: 600; }
  .total td { border-top: 2px solid #000; font-weight: 700; font-size: 17px; border-bottom: none; padding-top: 10px; }
  .total td:last-child { color: ${bal > 0 ? '#dc2626' : '#16a34a'}; }
  hr { margin: 20px 0; border: none; border-top: 1px dashed #999; }
  .footer { text-align: center; color: #999; font-size: 12px; margin-top: 16px; }
  @media print { body { padding: 20px; } }
</style></head><body>
  <h1>Ledger</h1>
  <div class="period">${label}</div>
  <h2 style="font-size:18px;margin-bottom:16px">${r.member}</h2>
  <table>
    <tr><td>Total Meals</td><td>${r.meals.toFixed(2)}</td></tr>
    <tr><td>Meal Bill</td><td style="color:${r.mealBill < 0 ? '#16a34a' : '#000'}">৳${fmt(Math.abs(r.mealBill))}${r.mealBill < 0 ? ' cr' : ''}</td></tr>
    <tr><td>Bazar Given</td><td>৳${fmt(r.bazar)}</td></tr>
    <tr><td>Utility Bill</td><td>৳${fmt(r.utilityBill)}</td></tr>
    <tr><td>Service Charge</td><td>৳${fmt(r.serviceCharge)}</td></tr>
    <tr><td>House Rent</td><td>৳${fmt(r.rent)}</td></tr>
    <tr class="total"><td>Net Payment</td><td>৳${fmt(Math.abs(bal))} ${balText}</td></tr>
  </table>
  <hr>
  <div class="footer">Generated by Mess Khata</div>
  <script>window.onload=function(){window.print();}<\/script>
</body></html>`;
  const w = window.open('', '_blank');
  w.document.write(html);
  w.document.close();
}

export default function SlipsSheet({ members, monthData, monthKey }) {
  const t = computeTotals(members, monthData);

  return (
    <div>
      <h2 className="section-title">Payment Slips</h2>
      <p style={{ fontSize: '.78rem', color: 'var(--text-soft)', marginBottom: 12 }}>
        Print or download slip per person.
      </p>
      {t.rows.map(r => (
        <div key={r.member} className="slip">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <h3 style={{ margin: 0 }}>{r.member}</h3>
            <button className="btn small secondary" onClick={() => printSlip(r, monthKey)}>🖨️ Print</button>
          </div>
          <div style={{ fontSize: '.8rem', color: 'var(--text-soft)', marginBottom: 8 }}>Current Month</div>
          <table>
            <tbody>
              <tr><td>Meals</td><td className="num">{r.meals.toFixed(2)}</td></tr>
              <tr><td>Meal Bill</td>
                <td className="num" style={{ color: r.mealBill < 0 ? 'var(--green)' : '' }}>
                  ৳{fmt(Math.abs(r.mealBill))}{r.mealBill < 0 ? ' cr' : ''}
                </td>
              </tr>
              <tr><td>Bazar Given</td><td className="num">৳{fmt(r.bazar)}</td></tr>
              <tr><td>Utility Bill</td><td className="num">৳{r.utilityBill}</td></tr>
              <tr><td>Service Charge</td><td className="num">৳{fmt(r.serviceCharge)}</td></tr>
              <tr><td>House Rent</td><td className="num">৳{fmt(r.rent)}</td></tr>
            </tbody>
          </table>
          <div className="net-payment">
            <span>Net Payment</span>
            <span className={r.total < 0 ? 'credit' : 'owed'}>৳{fmt(Math.abs(r.total))} {r.total > 0 ? 'due' : r.total < 0 ? 'extra' : ''}</span>
          </div>
        </div>
      ))}
    </div>
  );
}
